server:
  port: 8090
  servlet:
    context-path: /backen
jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/db_backen?userUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: 123456

filePath:   D:/work/view/ueditor/jsp/upload/image/
nginxPath:  http://192.168.199.231/ueditor/jsp/upload/image/